steps:
  # Step 1: Build Docker image for your Streamlit app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/doctigo-app', '.']

  # Step 2: Push Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/doctigo-app']

  # Step 3: Deploy updated container to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'doctigo-app',
        '--image', 'gcr.io/$PROJECT_ID/doctigo-app',
        '--region', 'asia-south1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '8080'
      ]

images:
  - 'gcr.io/$PROJECT_ID/doctigo-app'
